### ISSUE TITLE
Some code errors

### ISSUE THREAD

**Issue by projectTamaru** [sheran/bbt#2]
There were some code errors, especially in the lines where print was used. It was supposed to have brackets between the input text to be printed.

**Comment by sheran** [comment]
Thanks for your message! I wrote this quite some time ago using Python 2 and have not ported it to Python 3. Presumably this is why you say the text to be printed requires parentheses? If you think that there's a genuine error, however, can you point out the line numbers?

**Comment by projectTamaru** [comment]
I would like to make a fork of this to make it work on Python3! it could be used to retrieve long-lost pics on any Blackberry phones

**Comment by sheran** [comment]
Thank you for offering! Feel free to fork the project and port it to Python3. Let me know if you run into any issues.
